apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-server
  labels:
    role: nfs
spec:
  replicas: 2
  selector:
    matchLabels:
      role: nfs
  template:
    metadata:
      labels:
        role: nfs
    spec:
      containers:
      - name: nfs-server
        image: k8s.gcr.io/volume-nfs
        ports:
        - name: nfs
          containerPort: 2049
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /exports
          name: data
      volumes:
      - name: data
        hostPath:
          path: /home/ubuntu/data
          type: DirectoryOrCreate
          
---

kind: Service
apiVersion: v1
metadata:
  name: nfs-server
  labels:
    role: nfs
spec:
  type: ClusterIP
  selector:
    role: nfs
  ports:
    - name: tcp-2049
      port: 2049
  clusterIP: 10.96.1.10

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: data
spec:
  capacity:
    storage: 15Gi
  accessModes:
    - ReadOnlyMany
  nfs:
    server: 10.96.1.10
    path: /exports/ghrc38
---


apiVersion: v1
kind: PersistentVolume
metadata:
  name: results
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.96.1.10
    path: /exports/results

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data
spec:
  accessModes:
    - ReadOnlyMany
  storageClassName: ""
  resources:
    requests:
      storage: 10Gi
  volumeName: data

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: results
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 1Gi
  volumeName: results
  
