apiVersion: v1
kind: PersistentVolume
metadata:
  name: data
spec:
  capacity:
    storage: 15Gi
  accessModes:
    - ReadOnlyMany
  nfs:
<<<<<<< HEAD
    server: 172.31.29.200
    path: /home/ubuntu/data/data
=======
    server: <NFS-SERVER-IP>
    path: /home/ubuntu/data
>>>>>>> 6b7023e4b5da8956ee83958e6fb9c9a5a430caa3

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: results
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  nfs:
<<<<<<< HEAD
    server: 172.31.29.200
=======
    server: <NFS-SERVER-IP>
>>>>>>> 6b7023e4b5da8956ee83958e6fb9c9a5a430caa3
    path: /home/ubuntu/data/results

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data
spec:
  accessModes:
    - ReadOnlyMany
  storageClassName: ""
  resources:
    requests:
      storage: 5Gi
  volumeName: data

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: results
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 1Gi
  volumeName: results
