apiVersion: v1
kind: PersistentVolume
metadata:
  name: data
spec:
  capacity:
    storage: 15Gi
  accessModes:
    - ReadOnlyMany
  nfs:
    server: <NFS-SERVER-IP>
    path: /home/ubuntu/data

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: results
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: <NFS-SERVER-IP>
    path: /home/ubuntu/data/results

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data
spec:
  accessModes:
    - ReadOnlyMany
  storageClassName: ""
  resources:
    requests:
      storage: 5Gi
  volumeName: data

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: results
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 1Gi
  volumeName: results
